"""empty message

Revision ID: 1596c53b38ae
Revises: 42beb40b9d03
Create Date: 2023-06-16 21:54:37.591387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1596c53b38ae"
down_revision = "42beb40b9d03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column("highest_bid", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column("listings", sa.Column("bids_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings", "bids_count")
    op.drop_column("listings", "highest_bid")
    # ### end Alembic commands ###
