"""empty message

Revision ID: 2673fdb9002d
Revises: 8f4103312af7
Create Date: 2023-06-14 19:47:01.370799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2673fdb9002d"
down_revision = "8f4103312af7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_session_id"), "session", ["session_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_session_id"), table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
