"""empty message

Revision ID: 36994d1c6077
Revises: be17643aa9b1
Create Date: 2023-06-05 23:16:37.632404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36994d1c6077"
down_revision = "be17643aa9b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
