"""empty message

Revision ID: 3ae659e98154
Revises: d4a611a943b2
Create Date: 2023-06-03 22:47:35.680105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae659e98154'
down_revision = 'd4a611a943b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
