"""empty message

Revision ID: 42beb40b9d03
Revises: 962d74fec71f
Create Date: 2023-06-16 15:26:37.511324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42beb40b9d03"
down_revision = "962d74fec71f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
