"""empty message

Revision ID: 601e92853269
Revises: e31992459ff2
Create Date: 2023-06-16 22:03:33.380783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "601e92853269"
down_revision = "e31992459ff2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
