"""empty message

Revision ID: 8f4103312af7
Revises: 36994d1c6077
Create Date: 2023-06-05 23:21:42.555307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f4103312af7"
down_revision = "36994d1c6077"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
