"""empty message

Revision ID: be17643aa9b1
Revises: bd83a7d742dd
Create Date: 2023-06-05 22:54:11.882785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be17643aa9b1"
down_revision = "bd83a7d742dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
