"""empty message

Revision ID: d4a611a943b2
Revises: 1e81de8d6ad4
Create Date: 2023-06-03 22:10:29.779099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a611a943b2'
down_revision = '1e81de8d6ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
