"""empty message

Revision ID: d8872d8a1ea7
Revises: da6e4b582af5
Create Date: 2023-06-20 20:48:52.535564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8872d8a1ea7"
down_revision = "da6e4b582af5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("listings_image_id_fkey", "listings", type_="foreignkey")
    op.create_foreign_key(
        None, "listings", "files", ["image_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "listings", type_="foreignkey")
    op.create_foreign_key(
        "listings_image_id_fkey",
        "listings",
        "files",
        ["image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
