"""empty message

Revision ID: da6e4b582af5
Revises: 601e92853269
Create Date: 2023-06-20 17:33:13.689033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da6e4b582af5"
down_revision = "601e92853269"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
