"""empty message

Revision ID: e31992459ff2
Revises: 1596c53b38ae
Create Date: 2023-06-16 22:01:20.501707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e31992459ff2"
down_revision = "1596c53b38ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
